### ISSUE TITLE
Batch mode does not trigger longRunning onDestroy handlers

### ISSUE THREAD

**Issue by stephan-noel** [Farfetch/garment#31]
## Issue Report

Garment is not invoking the onDestroy handlers when a batch runner finishes executing.

## Expected Behavior

Garment should invoke onDestroy handlers when the first non longRunning task is in batch mode as well.

## Actual Behavior

In the following config , runner-wdio is run in batch mode.  When it ends however, runner-docker-compose and runner-web-scripts: serve (both which use context.longRunning), do not have their onDestroy handlers invoked.

![image](https://user-images.githubusercontent.com/34415120/103213754-926a3f00-4906-11eb-83fa-9d17ff57bbad.png)

**Comment by beshanoe** [comment]
@stephan-noel hey, Alex has opened a PR with the fix, but actually the whole idea of using in this case a batch runner doesn't make sense. Batch mode is created for the cases when we want to execute some heavy task for multiple projects. For example, in order to avoid running 20 jest instances, runner-jest works in a batch mode, meaning that all the actions which use it are extracted from the action graph and then passed together(batch) to a single runner-jest call, so we only run a single Jest instance for all the projects.
In your case, if you run `test-e2e` task for more than 1 project it'll fail cause it won't be able to start multiple `serve` and `docker-compose` on the same port. That's why you will either need to implement all those runners as batch or make the wdio runner not batch. The latter would be preferable at this stage because the former option would probably introduce more issues than solve

**Comment by stephan-noel** [comment]
Thanks for the explanation, I think I need to dig into batch mode a bit more, but yes you are right.  After checking with the team, it seems that we do need to restructure our garment tasks to make use of batch mode similar to jest, so I think we will have to go with option 1 and rewrite the first two runners as batch.
