### ISSUE TITLE
configFile option does not support npm module syntax

### ISSUE THREAD

**Issue by stephan-noel** [Farfetch/garment#7]
## Issue Report

`{{projectDir}}` is supported, however, npm module syntax ie, `@some-scope/tsconfig/tsconfig.node.json` is causing the error 
described here https://github.com/Farfetch/garment/issues/4 . 

## Expected Behavior

npm module syntax ie, `@some-scope/tsconfig/tsconfig.node.json` should be supported as tsc supports this in tsconfig.json files.

## Actual Behavior

You get this error: 

 ![image (9)](https://user-images.githubusercontent.com/34415120/88235414-be580900-cc72-11ea-8d8e-0eea346f80e7.png)

## Steps to Reproduce the Issue

1. Use npm module syntax either directly in the configFile option of the ts-runner or in the `extends` property of one of the tsconfig files.
2. Run the ts-runner

**Comment by stephan-noel** [comment]
I've got a manually tested fix, just need to make a unit test for it.  I will try to open the MR some time this week.

**Comment by beshanoe** [comment]
In order to support it in the configFile, there needs to be a change in the way path-options are resolved, and in case of "extends" inside tsconfig.json it needs to be done inside the ts-runner. I would for now focus on the latter as it's more used pattern. I don't know if there's a strong use case for passing an npm module to the configFile right away. Although it's probably nice to have feature

**Comment by stephan-noel** [comment]
Oh true.  I think I may be able to do it in the surrounding code.  I'll try out and test the direct option and see what I come up with.
